### ISSUE TITLE
Does not compile for Scala.js

### ISSUE THREAD

**Issue by Tamriel** [wvlet/airframe#111]
When using 
```
import wvlet.log._

Logger.setDefaultHandler(JSConsoleLogHandler())

class YourAppClass extends LogSupport {

  info("hello")
}
```
 I get `not found: value JSConsoleLogHandler`

**Comment by xerial** [comment]
To use JSConsoleLogHandler, you need to configure your build.sbt like this: 
```
libraryDependencies += "org.wvlet.airframe" %%% "airframe-log" % "0.24"
```

If you can share your build configuration, I would be able to comment more.

**Comment by Tamriel** [comment]
Thanks for you answer.
I used that line in my build.sbt, which looks like this: https://gist.github.com/Tamriel/b8d5a8a5f5102975ef7f9549a298ba82

**Comment by xerial** [comment]
Thanks!
For confirming the issue, I have created an example project that uses airframe-log in Scala.js #112, and found the Logger initialization code in the doc was wrong. 

I'll fix it. Thanks for reporting.

**Comment by xerial** [comment]
@Tamriel 

So the correct syntax was like this:
```scala
Logger.setDefaultHandler(new JSConsoleLogHandler()) 
```

**Comment by xerial** [comment]
However in the above example project, both styles works. So my guess is you are trying to use JSConsoleLogHandler in JVM project. This class is available only for Scala.js projects.

**Comment by Tamriel** [comment]
It does not work with the new syntax yet.
I am using a crossProject, but I have no special js folder.

**Comment by xerial** [comment]
The source code that uses JSConsoleLogHandler should be located in `js/src` folder. If you use it in `jvm/src` or `shared/src` it won't compile.

**Comment by Tamriel** [comment]
My project has the CrossType [Pure](https://github.com/scala-native/sbt-crossproject#crosstypes) and therefore no special js, jvm or shared folders.

**Comment by xerial** [comment]
@Tamriel Yes. That is the reason why your code doesn't compile. JSConsoleLogHandler is js-specific code.

**Comment by Tamriel** [comment]
The logger https://github.com/outr/scribe is able to do it with pure crosscompiled projects.
But nevermind, I will just use that logger.
Thanks for your work, for providing an open source library!

**Comment by xerial** [comment]
Yeah. It's a sort of design decision, and I can put a mock implementation of JSConsoleLogHandler for non-Scala.js projects, but if you want to customize colors, log message formats, etc, it will be anyway Scala.js specific unless we introduce some abstraction.
