### ISSUE TITLE
airframe-msgpack - 32 bit unsigned seconds timestamp

### ISSUE THREAD

**Issue by hsn10** [wvlet/airframe#1159]
Can you add support for timestamp _type 1_ - 32 bit unsigned seconds? It is most used by other msgpack software.

In trait packer you seems to support only _type 3_ - 64 bit seconds + 32 bitnano def packTimestamp(epochSecond: Long, nanoAdjustment: Int):

https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type

**Comment by xerial** [comment]
Internally airframe-msgpack automatically uses 32 bit timestamp if the value can be represented in 32-bit unixtime. 
https://github.com/wvlet/airframe/blob/b8525262896b9c950c7e2545b3e4cae41116eebb/airframe-msgpack/src/main/scala/wvlet/airframe/msgpack/spi/OffsetPacker.scala#L209

So if use packTimestamp(Instant.ofEpochSeconds(unixtime)), it uses 32-bit unsigned. 

Of course, if you want to guarantee using 32-bit timestamp, adding packUnixTimestamp(epochSeconds:Long) can be an option.

**Comment by xerial** [comment]
Let me know if this PR works for your use case https://github.com/wvlet/airframe/pull/1160

**Comment by hsn10** [comment]
Yes, it will work.

**Comment by xerial** [comment]
Thanks. Use packTimestamp(unixtime, 0) as a workaround until the next release (Maybe around July)
