### ISSUE TITLE
Support msgpack RPC services

### ISSUE THREAD

**Issue by hsn10** [wvlet/airframe#1165]
https://github.com/msgpack-rpc/msgpack-rpc/blob/master/spec.md

Can be this done in http library? I need just server side. In Java you pass object and url where to bind it to http server framework and any public object method can be invoked using msgpack RPC.

**Comment by hsn10** [comment]
In Scala we could support even Async functions returning Future and because replies has sequence number it would be possible to invoke object functions by wrapping them into Futures on server side.

**Comment by xerial** [comment]
@hsn10 Absolutely yes! It's not documented yet, but airframe-http already has MessagePack (or JSON)-based RPC implementation, which can be used for Scala.js too for server-browser interaction.

```scala
@RPC
trait MyAPI {
  // sync API. It's also possible to return Future for async RPC
  def hello(msg:String, ...): String = { ... }
}
```

- Use @RPC (of @Endpoint) to define endpoints in Scala functions 
- Use Accept: application/x-msgpack (or appliction/json) to specify which to use
- sbt-airframe plugin can generate HTTP client code for accessing these APIs. This supports both sync and Future-based async client generation.

**Comment by xerial** [comment]
Here is a small example that shows how to use airframe-rpc https://github.com/wvlet/airframe/tree/master/sbt-airframe/src/sbt-test/sbt-airframe/generate-client

**Comment by hsn10** [comment]
I will do my testing if wire format is compatible with C implementation.

**Comment by hsn10** [comment]
is Notification message (type 2) supported? I think it is to be used for async server push

**Comment by xerial** [comment]
@hsn10 No. Do you mean https://en.wikipedia.org/wiki/HTTP/2_Server_Push or https://developers.google.com/web/fundamentals/performance/http2#server_push?

I've studied a little bit about HTTP2 and supporting ServiceWorker, etc., but I have not yet determined how to support them.

**Comment by hsn10** [comment]
No HTTP/2 in msgpack-rpc specification under section Notification Message format is:

[2, "method name", [params,..] ]

**Comment by hsn10** [comment]
While reading https://github.com/nori0428/msgpack.rpc.js/blob/master/msgpack.rpc.js I discovered that in this msgpack client RPC library there is only support of sending notify events to server and not receiving them. Maybe I do not understand purpose of these messages yet. They also use WebSocket transportation.

**Comment by xerial** [comment]
ok. We have no plan to support the old RPC specification as is, which is already 8-year-old and I'm not sure who is actively using this protocol and have verified the effectiveness. Around that time, HTTP/2 was not popular. 

If we design async protocol now, we will take a different approach (e.g., multiplexing RPC messages and support bidirectional message transfer, etc.)

**Comment by xerial** [comment]
@hsn10 FYI, Airframe will support gRPC backend using MessagePack as an intermediate data format https://wvlet.org/airframe/docs/airframe-rpc#airframe-grpc

The performance seems promising. I could easily make thousands of RPC calls per second with gRPC and HTTP2. 

Let me close this ticket. For multiplexing RPC calls and introducing streaming support, using gRPC will be a quick path. Currently, airframe-grpc doesn't support streaming. We need to define a streaming interface for Scala.
