### ISSUE TITLE
MessageCodec.of[A] is missing :TypeTag

### ISSUE THREAD

**Issue by hsn10** [wvlet/airframe#1167]
other MessageCodec object methods has typetag annotation
I needed this change:
https://gitlab.com/hsn10/akka-http-msgpack/-/commit/fb4edc72db5289c28bdc1a528ebc90484b3a1347

to make msgpack serializer for Akka to work. If it had typetag on .of method, i expect that it would be done by compiler or at least I would get error - no typetag for T.

**Comment by xerial** [comment]
This is for supporting Scala.js, which has no TypeTag support.

We may be able to add such an interface only for JVM like airframe-codec/.jvm/ ...

**Comment by xerial** [comment]
TypeTag has been removed in Scala 3, so we will not support this
