### ISSUE TITLE
abt-airframe: Multiple routes error in multi-projects if impl in placed under the api definiton package

### ISSUE THREAD

**Issue by takezoe** [wvlet/airframe#1242]
I'm not sure exact conditions to reproduce. However, the keys are:

- Implementation of API is placed in the same or under the package where api trait is placed.
- Generate client in a different sbt sub-project from the above.

This project can reproduce: https://github.com/takezoe/airframe-http-plugin-repro

Of course, there are some workarounds:

- Place implementation in the different parent package.
- Separate api definition and impl to different sub-projects, and client project refers only api project.

However, it would be nice if we can use airframe-rpc-client without such special care.

**Comment by xerial** [comment]
Thanks. I'll take a look

**Comment by xerial** [comment]
https://github.com/wvlet/airframe/blob/a55cb68926c967fcac9bfd8ca2cbd439dba92031/airframe-http/.jvm/src/main/scala/wvlet/airframe/http/codegen/RouteScanner.scala

Currenlty, sbt-airframe plugin scans all classes under the specified package and create a Router from classes with `@RPC` annotation. In this case API and its impl classes both has `@RPC` annotation, so both classes are included to the same Router. It seems we need to extract only base classes which have `@RPC` annotation in the above RouteScanner code.

**Comment by takezoe** [comment]
Yeah, the current behavior is understandable. Mysteriously, it works if sbt-airframe plugin is enabled in the same projects with API and Impl classes (`api` project in this case).

**Comment by xerial** [comment]
With #1244, the compilation error of your sample project is fixed.

**Comment by takezoe** [comment]
Great thanks!
