### ISSUE TITLE
airframeHttpGenerateClient task prompt "command line is too long" on windows

### ISSUE THREAD

**Issue by 14sxlin** [wvlet/airframe#1447]
When executiong `airframeHttpGenerateClient` task, it will fail with info "命令行太长。", that is "command line is too long". It's causeed by the long "-cp" parameter of the "generate" comand.

![image](https://user-images.githubusercontent.com/13958137/105566102-57242a00-5d65-11eb-87d0-83e9e8ebf6a6.png)

The source code is here:
`wvlet.airframe.sbt.http.AirframeHttpPlugin.Keys#airframeHttpGenerateClient`

The limitation of windows command line length is here:
https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation

Maybe It's a good idea to package the dependency into a jar rather than use their paths directly.

To replay the issue, using the test project in https://github.com/wvlet/airframe/tree/master/sbt-airframe/src/sbt-test/sbt-airframe/generate-client on windows.

**Comment by xerial** [comment]
Thanks for the report. Since Java9, we can use https://docs.oracle.com/en/java/javase/14/docs/specs/man/java.html#java-command-line-argument-files. So instead of creating long command line arguments, we can dump it to a file, then run `java @commandline` 

Let me try this approach

**Comment by xerial** [comment]
Or we can support a file input in the generator command
