### ISSUE TITLE
getLoggerName JVM implementation wrongly assigns logger name when instantiated using bind

### ISSUE THREAD

**Issue by pbuszka14** [wvlet/airframe#170]
logger gets assigned name of "wvlet.airframe.SessionHolder" when a class (but not a trait) which uses LogSupport is instaniated via airframe bind[..].

```
class ClassA extends LogSupport {
 def test = {
  info("dummy)
  // wvlet.log.LogEnv#getLoggerName will return "wvlet.airframe.SessionHolder"
  // effectively logger here behaves as if it was a logger of wvlet.airframe.SessionHolder
 }
}

trait TraitA extends LogSupport {
 def test = {
   info("dummy)
   // wvlet.log.LogEnv#getLoggerName will return "TraitA"
   // and logger works as expected
 }
}

class B {
  lazy val aClass = bind[ClassA]
  lazy val aTrait = bind[TraitA]
 aClass.test
 aTrait.test
}

```

scala-js implementation does not suffer this problem
scala 12.5
airframe 0.41

Root cause is that a class with added SessionHolder by the binder is an anonymous class but does not contain a proper interface for the logger getLoggerName code to fall back. The only one appearing is  the SessionHolder trait added by the binder.

Proposed fix is to use scala-js implementation for both JVM and JS but I don't know if there are other reasons for separation of the implementation of this function.

**Comment by xerial** [comment]
Currently Airframe doesn't support bindings inside a class. 
```scala
class B {
  lazy val aClass = bind[ClassA] // This doesn't work
  lazy val aTrait = bind[TraitA]   //  This also doesn't work
 aClass.test
 aTrait.test
}
```

You need to inject dependencies through constructor parameters:
```scala
// This works with session.biuld[B]
class B(aClass:ClassA, aTrait:TraitA) {
aClass.test
 aTrait.test
}
```

Or changing the class B to trait will also work.

**Comment by pbuszka14** [comment]
Thanks for clarification
