### ISSUE TITLE
Nested bindings within Y fail when using bind[X].to[Y] in some cases

### ISSUE THREAD

**Issue by pbuszka14** [wvlet/airframe#171]
I found an odd behavior when constructing a service which uses other services and it failed randomly with MISSING_SESSION exception.

I narrowed down the problem to the scenario ilustrated by the test below. As I looked into the code it seems that bind[X]  does not generates session injecting code when injected class is abstract and expects a bind[X].to[Y] in the design.

It works nice but effectively the class Y which is instantied as result of bind[X[.to[Y] does not have a session in it. It works but only if class Y does not have to access the session.

On the other hand if I tried to make X non-abstract the bind[X].to[Y] had no effect. The class instantiated was X not Y. It probably warrants an exception if the design contains bind[X].to[Y] when X is a concrete class.

Both problems look like a bug to me but maybe I'm missing something about how this kind of pattern should be encoded in airframe.

```
import org.scalatest.{WordSpec, Matchers}
import wvlet.airframe._

trait HelloApi {
 def hello(): String
 def helloNoInnerService() = "NoInnerService"
}

class InnerHelloService {
  def innerHello() = "InnerHello"
}

class HelloApiImpl extends HelloApi {
  lazy val innerHelloService = bind[InnerHelloService]
  def hello() = innerHelloService.innerHello()
}


class AirframeTest extends WordSpec with Matchers {
  val design = newDesign
    .bind[InnerHelloService].toSingleton
    .bind[HelloApiImpl].toSingleton
    .bind[HelloApi].to[HelloApiImpl]

  "AirframeTest Trait API" should {
    "direct HelloApiImpl OK" in {
      val session = design.newSession
      val helloApi = session.build[HelloApiImpl]
      val helloAnswer = helloApi.hello()
      helloAnswer shouldBe ("InnerHello")
    }

    "prebuild singleton OK" in {
      val session = design.newSession
      val helloApiImpl = session.build[HelloApiImpl]
      val helloApi = session.build[HelloApi]
      val helloAnswer = helloApi.hello()
      helloAnswer shouldBe ("InnerHello")
    }

    "innerService not binded OK" in {
      val session = design.newSession
      val helloApi = session.build[HelloApi]
      val helloAnswer = helloApi.helloNoInnerService()
      helloAnswer shouldBe ("NoInnerService")
    }

    "InnerService constructed within Fails" in {
      val session = design.newSession
      val helloApi = session.build[HelloApi]
      val helloAnswer = helloApi.hello()
      helloAnswer shouldBe ("InnerHello")
    }
  }
}
```

**Comment by xerial** [comment]
Thanks for reporting. I'll check this shortly

**Comment by xerial** [comment]
@pbuszka14 
Currently we are not supporting injecting a session to concrete classes like HelloApiImpl. I think if you change this class to a trait, it will work as expected. 

```scala
trait HelloApiImpl extends HelloApi {
  lazy val innerHelloService = bind[InnerHelloService]
  def hello() = innerHelloService.innerHello()
}
```

**Comment by pbuszka14** [comment]
OK, when I change all classes to trait it works as expected. I was misled as it works on the first level if it is a class with a default constructor. Thanks for clarification
