### ISSUE TITLE
airframe-msgpack - Unpacker.tryUnpackNil fails

### ISSUE THREAD

**Issue by fizzy33** [wvlet/airframe#1769]
Experiencing issues where Unpacker.tryUnpackNil throws an exception (instead of returning false) if there isn't enough data left in the stream.

MessagePack core does not have this issue it first checks to see if there is enough space in the buffer first.

**Comment by fizzy33** [comment]
PureScalaBufferUnpacker throws an exception and UnpackerImpl returns false.  For the case where you call the method when you are at the end of the input.

I can provide a PR to fix PureScalaBufferUnpacker.tryUnpackNil  returns false if at the end of input

**Comment by xerial** [comment]
Thanks for the report. Having a PR would be great.

**Comment by xerial** [comment]
@fizzy33 Second thought. It seems calling tryUnpackNil without checking the result of hasNext is an unexpected usage. Could you use hasNext first?

**Comment by fizzy33** [comment]
Of course that is what I/we are doing.  The issue arised because there are two implementations and one does the check for you and the one I cited here does not.  

Seems like the two options are 
1) do the check intnerally
2) document tryUnpackNil  that it can fail at end of data

**Comment by xerial** [comment]
@fizzy33 I still don't understand the whole context. I tried to reproduce your situation at #1787, but it's working as expected:
```scala
    val unpacker = MessagePack.newUnpacker(Array.empty[Byte])
    unpacker.hasNext // false
    unpacker.tryUnpackNil // throws InsufficientBufferException. This should not be called when hasNext returns false
```

All of msgpack-core (java version), PureScalaUnpacker, MessagePack.newUnpacker, throws the exception when there is no more byte

**Comment by xerial** [comment]
Let me close the issue as it's not reproducible in #1787. If you have a reproduction of the issue, reopen the ticket.
