### ISSUE TITLE
Absolute paths in generated script

### ISSUE THREAD

**Issue by silizza** [wvlet/airframe#2326]
Hi!
We use airframe logger in scala js project and noticed that compiled js file contains the absolute paths of local file system, generated by airframe logger.
`Lwvlet_log_LogSource("/Users/liza/Documents/.../src/main/scala/..../package.scala", "package.scala", 41, 17)`

Is there a way to avoid using of absolute paths?

**Comment by xerial** [comment]
Thanks for the heads up. This is actually annoying when building Scala.js applications in terms of security and code size.

The full source code paths will be removed in the next version of airframe. #2330

**Comment by xerial** [comment]
The fix will be available in 22.7.3

**Comment by silizza** [comment]
@xerial I have updated the version of airframe logger to 22.7.3 (also have tried 22.9.0) in my project. But I still see absolute paths in my js file.
Maybe i'm doing something wrong?
Thank you
