### ISSUE TITLE
Is Design.blanc intentionally named?

### ISSUE THREAD

**Issue by seratch** [wvlet/airframe#256]
I'm afraid that `Design.blank` is more natural in English. https://github.com/wvlet/airframe/blob/v0.66/airframe/src/main/scala/wvlet/airframe/Design.scala#L171

I suggest to have a transition period as below. Accroding to the comment, the `Design` instance is "empty". Thus, `Design.empty` may be also good.
```scala
object Design {

  /**
    * Empty design.
    */
  @deprecated(message = "Use Design.blank instead", since = "0.xx")
  val blanc: Design = new Design(new DesignOptions(), Vector.empty) // Use Vector for better append performance
  val blank: Design = blanc
}
```

If I'm wrong, please correct me.

**Comment by xerial** [comment]
blanc is a French word, meaning white. Yes. It’s `blank` in English.

Design.newDesign (defined in airframe package) is a preferred method. We have not seen use cases of empty designs so far. So I prefer just making this a private variable for internal use:
```
private[airframe] val blanc = ... 
```

**Comment by seratch** [comment]
Thanks, I've submitted a pull request on this.
