### ISSUE TITLE
airframe-sql: Unresolve AllColumns as a pre-process

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#2743]
After rewriting the input relation, we need to re-resolve AllColumn expression if it already has been resolved. TypeResolver should detect mismatches of resolved columns in AllColumn and the inputAttribute.

**Comment by takezoe** [comment]
I haven't tried it yet, just ignoring `None` here isn't enough?
https://github.com/wvlet/airframe/blob/4ba9fd098e26fd731a41b1d17132a8ca353bad7f/airframe-sql/src/main/scala/wvlet/airframe/sql/analyzer/TypeResolver.scala#L449

**Comment by xerial** [comment]
AllColumns.input/outputColumns and sourceColumns also use AllColumns.columns parameter. Some PID columns could not be found because of this.

**Comment by takezoe** [comment]
I see. Thank you for checking!
