### ISSUE TITLE
bindFactory causes compilation error

### ISSUE THREAD

**Issue by takezoe** [wvlet/airframe#357]
```scala
package com.github.takezoe
import wvlet.airframe._

trait Logger {
  val tag: String = bind[String]
}

trait LoggerService {
  val factory = bindFactory[String => Logger]
}
```

This code causes a following compilation error.

```
value createNewInstanceOf in trait Session cannot be accessed in wvlet.airframe.Session
```

If above code is defined under `wvlet.airframe` package, it can be compiled.

**Comment by takezoe** [comment]
`Session#createNewInstanceOf()` is actually package private. It looks like expanded macros are referring this method.

https://github.com/wvlet/airframe/blob/bc6b17226c0f1e10d640fa177d22804669f2dd00/airframe/src/main/scala/wvlet/airframe/Session.scala#L66-L67

**Comment by xerial** [comment]
@takezoe Thanks for the report.
Then we need to add a helper method to access these methods here:
https://github.com/wvlet/airframe/blob/bc6b17226c0f1e10d640fa177d22804669f2dd00/airframe/src/main/scala/wvlet/airframe/Session.scala#L138

**Comment by takezoe** [comment]
I see. Let me try to fix.
