### ISSUE TITLE
Wrong number of arguments when MessageCodecFactory tries to parse JSON

### ISSUE THREAD

**Issue by Lewuathe** [wvlet/airframe#372]
We have the following case class.

```
case class InstanceIdentity(
  local_hostname: String,
  local_ipv4: String
)
```

When we try to parse the following JSON with MessageCodecFactory like this, it throws `IllegalArgumentException`.
```
{
    "account": "XXXXXXXXX",
    "availability_zone": "XXXX",
    "cloud": "aws",
    "instance_id": "i-XXXXXX",
    "local_hostname": "ip-XXXXXXX.ec2.internal",
    "local_ipv4": "XXX.XX.XX.XXX",
    "region": "us-east-1",
    "target": "XXXX"
}
```

```
val codecFactory = MessageCodecFactory.defaultFactory.withObjectMapCodec
def codec(implicit tag: TypeTag[InstanceIdentity]) = codecFactory.of[InstanceIdentity]

val msgPack = JSONCodec.toMsgPack(jsonStr)
val ret = codec.unpackBytes(msgPack, 0, msgPack.length)
```

```
2019-01-30 14:33:50.556+0900  warn [wvlet.airframe.surface.reflect.ReflectSurfaceFactory$RuntimeGenericSurface]
Failed to instantiate Object: [java.lang.IllegalArgumentException] wrong number of arguments
args:[ip-XXXXXXX.ec2.internal, XXX.XX.XX.XXX]  - (ReflectSurfaceFactory.scala:491)
```

Even if I extended `InstanceIdentity` to have all 8 properties but it still throws `IllegalArgumentException`. So I guess the problem is not the number of arguments. 

That's the log in trace level. Surface tries to create an object from the constructor of `java.lang.Object` that 's the reason why it fails to instantiate the class. 

```
2019-01-30 16:07:35.017+0900 trace [wvlet.airframe.surface.reflect.ReflectSurfaceFactory$RuntimeGenericSurface] build java.lang.Object with args: .....  - (ReflectSurfaceFactory.scala:480)
```

**Comment by xerial** [comment]
I think your InstanceIdenty class actually has 3 or more constructor arguments. I guess it might be defined inside another class? 

You can check the JVM byte code of InstanceIdenty class with javap. It will give you much more detail.

**Comment by xerial** [comment]
Ok. The problem is TypeTag reference is not resolved, and java.lang.Object is used for building the codec.

**Comment by Lewuathe** [comment]
The main problem of the missing surface was caused by the class loader issue by old sbt. Upgrading the sbt to 1.2.7 resolved the issue. Thanks. I'll close this.
