### ISSUE TITLE
airspec: Allow reusing test specs

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#597]
To reuse test functions, we can use the return value of test method like this:

__Idea A__
```scala
class Fixture[A](data:Seq[A]) extends AirSpec {
   def test1: Unit = { data shouldNotBe empty  }
   def test2: Unit = { data.length shouldBe data.size }
}

class MyTest extends AirSpec {
   def testIntSeq: AirSpec = new Fixture(Seq(1, 2, 3)) // Run the returned spec
   def testStringSeq: AirSpec = new Fixture(Seq("a", "b")) // Run the returned spec
}
```

If `Seq[AirSpec]` is returned, it should run this sequence of test specs.

__idea B__
Another approach is passing a test context through DI, then allow running new AirSpec:
```scala
def test(context:Context): Unit = {
  context.run(new Fixture(Seq(1, 2, 3)) 
  context.run(new Fixture(Seq("a", "b"))
}
```

- It seems idea B is more straightforward 
- Technically speaking, B is better since we can get a Surface of Fixture using `def run[A <: AirSpec](newSpec:A)` to get a list of test methods.

**Comment by xerial** [comment]
@takezoe Which do you prefer?

**Comment by xerial** [comment]
Actually I've concluded using B is better for sharing a global env (e.g., server process, complex service setup) and for allow nesting test cases in a functional manner.

**Comment by takezoe** [comment]
Simply create another method and call it from a test case with data as arguments doesn't work?

**Comment by xerial** [comment]
No, it will not work. 

This is because if we call functions in other class instances manually, there will be no way to tell which test methods were processed to AirSpecTask and AirSpecRunner. So it becomes difficult to count the number of successful and failed tests to the testing framework.

So calling the methods in AirSpec instances should be the responsibility of AirSpecTask (implementing sbt.testing.Task).

**Comment by takezoe** [comment]
I meant they would be separated test cases as:

```scala
def test(context: Context) = {
 // test using data
}

test("test1"){
  test(new Context())
}

test("test2"){
  test(new Context())
}
```

**Comment by xerial** [comment]
Run fixtures as individual test cases would be possible like:
```scala
def testIntSeq(context:Context) {  context.run(new Fixture(Seq(1, 2, 3)) }
def testStringSeq(context:Context) {  context.run(new Fixture(Seq("a", "b")) }
```
or an alternative approach is setting the context as a constructor parameter:
```scala
class MyTest(context:Context) extends AirSpec {
   private def test(fixture:Fixture) = context.run(fixture)
   def testIntSeq: Unit = test(new Fixture(Seq(1, 2, 3))
   def testStringSeq: Unit =test(new Fixture(Seq("a", "b"))
}
```

The general method scope usage of airspec is as follows:
- public methods: test cases
- protected/private methods: utility methods

**Comment by takezoe** [comment]
Probably, I was confused about the role of `Fixture` and `Context` in my previous example.

```scala
test(new Fixture(Seq(1, 2, 3))
```

returns three specs?

**Comment by xerial** [comment]
Let me define some terminologies to make clear the meanings:
- Context (or a test runner) is necessary to report test results (e.g., AirSpecTask, AirSpecRunner)
- Spec (or a test suite) is a set of public test methods (cases)
- Fixture is a template for defining tests as in ScalaTest http://www.scalatest.org/user_guide/sharing_fixtures
- Test methods can return arbitrary values. In the above example(s), `test(Fixture or AirSpec)` is just a utility method. 

So `test(new Fixture(Seq(1, 2, 3))` returns nothing. It will report test results to the context.

**Comment by takezoe** [comment]
Ah, `Fixture` is a set of test cases with test data. My understanding was that it's just a set of test data. I must have looked at the initial example carefully. Now I got you completely.

I think B is more flexible and proceduable, and A is more decalative and functional. What the functional manner do you mean in B?

**Comment by xerial** [comment]
Thanks. What I meant with _functional_ is just calling test specs as functions like `context.run(test_spec_class)`. If DI is necessary we can add `context.run[A <: AirSpec]` function.

**Comment by takezoe** [comment]
Thanks for your explanation. Now I get fully understanding! Finally, I prefer B for its flexibility :-)

**Comment by xerial** [comment]
Done in #602
