### ISSUE TITLE
airframe-http: Filter doesn't work for nonexistent routes

### ISSUE THREAD

**Issue by takezoe** [wvlet/airframe#840]
Currently, airframe-http's filter mechanism works for only defined routes. It restricts filter use cases. If it will work for all request, we will do the following things using a filter:

- Route unexistent paths by rewriting a request to existing paths in a filter
- Respond static contents based on requested paths from a filter

Also, the application-wide fallback mechanism might be helpful in some cases.

We can do them using Finagle native stuff for now, but it would be nice if airframe-http will support them.

**Comment by xerial** [comment]
I'll add this feature soon as I'm now working on StaticContentFilter

**Comment by xerial** [comment]
cc: @shimamoto

**Comment by xerial** [comment]
- StaticContent can be served without supporting leaf filter #843 
- Added leaf filter support in #844
