### ISSUE TITLE
airframe-log Publish for 2.13.1 and Scala.js

### ISSUE THREAD

**Issue by andreaTP** [wvlet/airframe#868]
Currently `airframe-log` is published for Scala.js and Scala 2.13.0-M4.
I started using this library as backend for Akka.Js and is therefore needed to publish for Scala 2.13

Thanks a lot for the great library!

**Comment by xerial** [comment]
The latest version of airframe-log has been available even for Scala 2.13, Scala.js 0.6.x, 1.0.0-M2 for a while:
https://search.maven.org/artifact/org.wvlet.airframe/airframe-log_2.13/19.12.3/jar

**Comment by xerial** [comment]
@andreaTP Do you mean the combination of Scala 2.13.1 + Scala.js 0.6.x or 1.0.0-x? http://repo1.maven.org/maven2/org/wvlet/airframe/

It would be possible to publish jars for this combination by simply tweaking the release script in GitHub Action.

**Comment by andreaTP** [comment]
correct the combination that I need is:
`Scala 2.13.1 + Scala.js 0.6.x`

I'm not familiar with Actions, but I would take a look in case eventually.

**Comment by xerial** [comment]
@andreaTP No worry. Let me work on this.

**Comment by andreaTP** [comment]
started something here:
https://github.com/wvlet/airframe/pull/869

but haven't checked nothing about.
Thanks a lot for the support!

**Comment by andreaTP** [comment]
Thanks a lot!

**Comment by xerial** [comment]
version 19.12.4 with Scala 2.13 + Scala.js 0.6/1.0.0-RC2 will be available synchronized to Maven central soon.
