### ISSUE TITLE
airspec: Callling scalaJsSupport is a bit verbose and confusing

### ISSUE THREAD

**Issue by exoego** [wvlet/airframe#906]
To use airspec on Scala.js, is is required to invoke `scalaJsSupport` in test code.

https://github.com/wvlet/airframe/blob/9277263b0d507ea7459a12fef82d301395fd3463/airspec/src/test/scala/examples/TestSpec.scala#L24-L25

The reason is mentoined in below

> https://github.com/wvlet/airframe/blob/master/docs/airspec.md
> This is because Scala.js has no runtime reflection to find methods in AirSpec classes, so we need to provide method data by calling `scalaJsSupport`.
> Internally this will generate `MethodSurface`s (airframe-surface), so that AirSpec can find test methods at runtime. Calling `scalaJsSupport` has no effect in Scala JVM platform, so you can use the same test spec both for Scala and Scala.js.

I think this is..,

* A bit verbose.  
    * Adding `scalaNativeSupport` when airspec support Scala Native ? 
* Confusing for airspec beginner, specially when migrating from scalatest, which does not require extra step like `scalaJsSupport`.
     * Test code is succesfully compiled without `scalaJsSupport`, but no tests run at all !!  
     * I spent several hours to figure out `scalaJsSupport` is required...

It would be great if `scalaJsSupport` is deprecated ang gone.
Regarding "runtime reflection in Scala.js", [portable-scala-reflect](https://github.com/portable-scala/portable-scala-reflect) might help.

Or, it may be OK if airspec warns like `No test classes with `scalaJsSupport` found. See https//.... `.

**Comment by xerial** [comment]
The latest version of Airframe supports `test(...) { ... }` syntax, which doesn't require scalaJsSupport call. 

In the documentation, I added this requirement at the very beginning of the tutorial so that Scala.js users can be aware of it. That's sad you wasted your time. I'm wondering how did you start writing test with AirSpec (e.g., reading doc?) This input will be helpful to improve the documentation.

I've also tried various approaches to remove the requirement of scalaJsSupport, but it's technically impossible for now as Scala.js (and portable-reflection) cannot find methods defined in child classes extending AirSpec trait.

**Comment by xerial** [comment]
Showing a warning message to suggest adding scalaJsSupport would be a good idea if no tests can be found in Scala.js.

**Comment by exoego** [comment]
> I'm wondering how did you start writing test with AirSpec (e.g., reading doc?) 

Sorry, this time I was too lazy so skipped reading the docs 😖 

1. I just add `airspec` as dependency to a fresh project.
2. Import `AirSpec` and other types by following IDE's code completion
3. Add a simple test

I did not imagine that special treatment needed.

**Comment by xerial** [comment]
Thanks. I agree that adding scalaJsSupport is a bit annoying. Personally, I've started using only test(...) method for Scala.js.

- Showing `test(...)` function first will be helpful for new users to avoid such confusion.
- Adding a warning message when scalaJsSupport is missing.

**Comment by xerial** [comment]
With #909, if no test case is found, a warning message will be shown. Actually some test cases of AirSpec itself were also missing `scalaJsSupport` 😅
