### ISSUE TITLE
TimeVectorTest started failing on or after 2020's leap day

### ISSUE THREAD

**Issue by SethTisue** [wvlet/airframe#953]
this turned up in the community build (https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/5553/artifact/logs/airframe-build.log) but is also reproducible outside it 

if you're not able to reproduce it, well, who knows, perhaps it's time-zone-dependent, or perhaps the problem only exists during a particular 24-hour window :-)

**Comment by xerial** [comment]
Thanks for reporting. I think I've fixed this issue yesterday (in the latest master) https://github.com/wvlet/airframe/commit/70a393eab3fc4a854f0964fde032b576acb44312#diff-5dc37e361c9109e1e7f38692b3f3c321R24

**Comment by SethTisue** [comment]
That is the commit I am using, I double-checked just now, and it fails for me.

Presently in the time zone I am in (Switzerland), it is Mar 1 1:09am.

```
~/airframe % git show | head -n 3
commit 70a393eab3fc4a854f0964fde032b576acb44312
Author: Taro L. Saito <leo@xerial.org>
Date:   Sat Feb 29 00:36:30 2020 -0800
~/airframe % sbt
[info] Loading settings for project airframe-build from plugin.sbt,metals.sbt ...
[info] Loading project definition from /Users/tisue/airframe/project
[info] Loading settings for project root from build.sbt ...
[info] Resolving key references (37172 settings) ...
[info] Set current project to airframe-root (in build file:/Users/tisue/airframe/)
[info] sbt server started at local:///Users/tisue/.sbt/1.0/server/1b358a8eae698db223af/sock
sbt:airframe-root> metricsJVM/testOnly *TimeVectorTest
TimeVectorTest:
 - succinct time window unit 43.82ms << failed: 31d didn't match with 1M (TimeVectorTest.scala:29)
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error] 	wvlet.airframe.metrics.TimeVectorTest
[error] (metricsJVM / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 4 s, completed Mar 1, 2020 1:10:48 AM
```

**Comment by xerial** [comment]
I see. It's another bug in the test case that depends on a specific time zone.  I'll fix that too.

**Comment by xerial** [comment]
@SethTisue I hope the latest master commit will fix the issue. I found a part where a fixed timezone is not properly used.

**Comment by SethTisue** [comment]
green again, on my laptop anyway! :+1:

**Comment by SethTisue** [comment]
and here, too https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/5559/console (after scala/community-build@1db0d1ad92ef930c8d6ea3898d1aeed1c2b1fe2e)
